// <auto-generated />
using System;
using DesignHelper.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesignHelper.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.AwardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Awards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Best Architecture Award 2022"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Best Interior Design Award 2022"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Best Visualization Award 2022"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Best Photography Award 2022"
                        },
                        new
                        {
                            Id = 5,
                            Name = "No awards"
                        });
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Interior Design"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Visualization"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Photography"
                        });
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddToFavouritesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AwardId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TopRatedEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddToFavouritesId");

                    b.HasIndex("AwardId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopRatedEntityId");

                    b.ToTable("ProjectsEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 5900.0,
                            Author = "LUKSTUDIO",
                            AwardId = 2,
                            CategoryId = 2,
                            Description = "Cultivating elegance in the everyday. Located in the North Bund of Hongkou District, Hall of the Sun is a 180,000 square meter commercial hub with an emphasis of nature in the design, including its curvilinear facade and a 3-storey-high biophilic food hall under Shanghai’s largest skylight roof canopy. Informed by the organic architecture, Lukstudio has extended the concept of nature and vitality into the public interior spaces.",
                            ImageUrl = "https://amazingarchitecture.com/storage/3335/responsive-images/1-refining_the_ordinary_lukstudio_shanghai___media_library_original_1343_755.jpg",
                            IsActive = true,
                            Location = "No. 181 Rui Hong Road, Hong Kou District, Shanghai, China",
                            Rating = 7.9m,
                            Title = "Refining the Ordinary"
                        },
                        new
                        {
                            Id = 2,
                            Area = 2360.0,
                            Author = "Colega Architects",
                            AwardId = 5,
                            CategoryId = 1,
                            Description = "This full gut remodel was realized for a design minded couple moving from New York back to LA. Making the transition back to sunny California, the couple had visions of keeping doors and windows open year-round. Self-proclaimed foodies, they were looking forward to weekend gatherings and being able to entertain inside and out. They purchased a home that had the square footage and lot size they wanted but lacked the aesthetics, flow and functions they sought. Modern, warm and uncluttered was their vision. Without adding a square foot, the existing house was transformed from a “drive by - don’t notice you” tired, tract home, into a custom, “that’s a remodel?” modern home that fully encompassed the warmth of family life with the modern aesthetic the couple was looking for.",
                            ImageUrl = "https://amazingarchitecture.com/storage/3427/responsive-images/crestridge_residence_colega_architects_california___media_library_original_1344_756.jpg",
                            IsActive = true,
                            Location = "Rancho Palos Verdes, California, USA",
                            Rating = 9.1m,
                            Title = "Crestridge Residence"
                        },
                        new
                        {
                            Id = 3,
                            Area = 6230.0,
                            Author = "AshariArchitects",
                            AwardId = 3,
                            CategoryId = 3,
                            Description = "The development of Kish in terms of tourism has led to the construction of new urban texture and buildings in the city to attract tourists and it can be noted that hotels are a potential platform that attracts tourists in the city texture according to their architectural-environmental factors.",
                            ImageUrl = "https://amazingarchitecture.com/storage/3369/responsive-images/1-armitaj_hotel_kish_island_ashariarchitects___media_library_original_1344_756.jpg",
                            IsActive = true,
                            Location = "Kish Island, Iran",
                            Rating = 8.3m,
                            Title = "Armitaj Hotel"
                        },
                        new
                        {
                            Id = 4,
                            Area = 385.0,
                            Author = "Maria Eirini Moschona",
                            AwardId = 5,
                            CategoryId = 4,
                            Description = "Villa Lavante is a luxury holiday home whose construction was completed in July 2019. It is located within a complex consisting of two adjoining and fully equipped and furnished luxury villas (Villa Lavante with an independent guest house and Villa Rosmarina). Each has its own large pool. The two villas are separated by a long stone fence.",
                            ImageUrl = "https://amazingarchitecture.com/storage/2288/responsive-images/villa_lavante_antiparos_greece_maria_eirini_moschona-___media_library_original_1344_756.jpg",
                            IsActive = true,
                            Location = "Antiparos, Greece",
                            Rating = 7.9m,
                            Title = "Villa Lavante"
                        },
                        new
                        {
                            Id = 5,
                            Area = 9800.0,
                            Author = "Waechter Architecture",
                            AwardId = 1,
                            CategoryId = 1,
                            Description = "The Furioso Vineyards project consists of the renovation and expansion of an existing winery, including the addition of a new tasting room and public amenity spaces. The original Furioso estate, located in the heart of Oregon’s wine country, was made up of a series of disconnected utilitarian structures scattered across its property, including a steel-shed winery, various storage facilities, outdoor crush pad, and an adjacent residence. Built in disparate styles and materials, the estate lacked a cohesive identity. In addition, although completely surrounded by vineyards, the buildings turned their backs on the landscape, instead focusing on internal production.",
                            ImageUrl = "https://amazingarchitecture.com/storage/3278/responsive-images/1-furioso_vineyards_waechter_architecture_dundee___media_library_original_1344_756.jpg",
                            IsActive = true,
                            Location = "Dundee, Oregon, USA",
                            Rating = 9.4m,
                            Title = "Furioso Vineyards"
                        },
                        new
                        {
                            Id = 6,
                            Area = 120.0,
                            Author = "Minus Workshop",
                            AwardId = 5,
                            CategoryId = 2,
                            Description = "“Zen Oasis” - A home gateway infused with Japanese aesthetics designed by Minus Workshop. The founder of Minus Workshop, Kevin Yiu has long been inspired by Eastern philosophies. He has taken over this residential design project into a modified version of the spirit of zen in Japan for a family who loves Japanese culture and wants a respite from the hustle and bustle of city life. With the simple three worded design brief “Japanese, zen and calm” to request Kevin to design his 120 square metre apartment. As a result, Yiu also breaks through the paradox between how we imagine stereotypical Japanese minimalism.",
                            ImageUrl = "https://amazingarchitecture.com/storage/2613/responsive-images/zen_oasis_minus_workshop_hong_kong___media_library_original_1344_756.jpg",
                            IsActive = true,
                            Location = "The Pavilion Bay, New Territories, Hong Kong",
                            Rating = 5.9m,
                            Title = "Zen Oasis"
                        },
                        new
                        {
                            Id = 7,
                            Area = 119608.0,
                            Author = "Aedas",
                            AwardId = 5,
                            CategoryId = 3,
                            Description = "Wenzhou is planned to be one of the global high-tech cities by establishing Wenzhou Innovaland. The start-up zone integrates technology, financial, wellness and education, creating a mixed-use innovative hub in Wenzhou. Aedas Executive Director Yaochun Wen and Global Design Principal Dr. Andy Wen have jointly led the team to create a pioneering space in the zone.",
                            ImageUrl = "https://amazingarchitecture.com/storage/3212/responsive-images/wenzhou_innovaland_start_up_zone_aedas___media_library_original_1344_756.jpg",
                            IsActive = true,
                            Location = "Wenzhou, China",
                            Rating = 8.9m,
                            Title = "Wenzhou Innovaland Start-Up Zone"
                        },
                        new
                        {
                            Id = 8,
                            Area = 289.0,
                            Author = "Vivien Renziehausen",
                            AwardId = 5,
                            CategoryId = 4,
                            Description = "German hotel & architecture photographer Vivien Renziehausen portrayed the newly built company building of Plangrad Architects in Bremen, Germany. The building was designed and planned by the respective company itself. The concept of an open office whilst still having the privacy of your own office space has been greatly achieved through large glass fronts both on the outside and inside of the building. Symmetry and clear forms and structures dominate the interior and exterior design what made it technically challenging to photograph. Still, Vivien skillfully managed to capture and showcase the light and airy atmosphere within the straight architectural concept.",
                            ImageUrl = "https://amazingarchitecture.com/storage/3059/responsive-images/plangrad_architects_vivien_renziehausen_bremen_germany___media_library_original_1344_756.jpg",
                            IsActive = true,
                            Location = "Bremen, Germany",
                            Rating = 6.8m,
                            Title = "Plangrad Architects"
                        });
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.ProjectToolsUsed", b =>
                {
                    b.Property<int>("ProjectsEntityId")
                        .HasColumnType("int");

                    b.Property<int>("ToolsUsedId")
                        .HasColumnType("int");

                    b.HasKey("ProjectsEntityId", "ToolsUsedId");

                    b.HasIndex("ToolsUsedId");

                    b.ToTable("ProjectToolsUsed");

                    b.HasData(
                        new
                        {
                            ProjectsEntityId = 1,
                            ToolsUsedId = 1
                        },
                        new
                        {
                            ProjectsEntityId = 1,
                            ToolsUsedId = 2
                        },
                        new
                        {
                            ProjectsEntityId = 1,
                            ToolsUsedId = 6
                        },
                        new
                        {
                            ProjectsEntityId = 1,
                            ToolsUsedId = 7
                        },
                        new
                        {
                            ProjectsEntityId = 2,
                            ToolsUsedId = 2
                        },
                        new
                        {
                            ProjectsEntityId = 2,
                            ToolsUsedId = 3
                        },
                        new
                        {
                            ProjectsEntityId = 2,
                            ToolsUsedId = 5
                        },
                        new
                        {
                            ProjectsEntityId = 2,
                            ToolsUsedId = 6
                        },
                        new
                        {
                            ProjectsEntityId = 2,
                            ToolsUsedId = 8
                        },
                        new
                        {
                            ProjectsEntityId = 3,
                            ToolsUsedId = 1
                        },
                        new
                        {
                            ProjectsEntityId = 3,
                            ToolsUsedId = 4
                        },
                        new
                        {
                            ProjectsEntityId = 3,
                            ToolsUsedId = 6
                        },
                        new
                        {
                            ProjectsEntityId = 3,
                            ToolsUsedId = 8
                        },
                        new
                        {
                            ProjectsEntityId = 4,
                            ToolsUsedId = 9
                        },
                        new
                        {
                            ProjectsEntityId = 5,
                            ToolsUsedId = 3
                        },
                        new
                        {
                            ProjectsEntityId = 5,
                            ToolsUsedId = 1
                        },
                        new
                        {
                            ProjectsEntityId = 5,
                            ToolsUsedId = 5
                        },
                        new
                        {
                            ProjectsEntityId = 5,
                            ToolsUsedId = 6
                        },
                        new
                        {
                            ProjectsEntityId = 5,
                            ToolsUsedId = 8
                        },
                        new
                        {
                            ProjectsEntityId = 6,
                            ToolsUsedId = 2
                        },
                        new
                        {
                            ProjectsEntityId = 6,
                            ToolsUsedId = 4
                        },
                        new
                        {
                            ProjectsEntityId = 6,
                            ToolsUsedId = 7
                        },
                        new
                        {
                            ProjectsEntityId = 6,
                            ToolsUsedId = 6
                        },
                        new
                        {
                            ProjectsEntityId = 7,
                            ToolsUsedId = 1
                        },
                        new
                        {
                            ProjectsEntityId = 7,
                            ToolsUsedId = 2
                        },
                        new
                        {
                            ProjectsEntityId = 7,
                            ToolsUsedId = 5
                        },
                        new
                        {
                            ProjectsEntityId = 7,
                            ToolsUsedId = 3
                        },
                        new
                        {
                            ProjectsEntityId = 7,
                            ToolsUsedId = 8
                        },
                        new
                        {
                            ProjectsEntityId = 7,
                            ToolsUsedId = 6
                        },
                        new
                        {
                            ProjectsEntityId = 8,
                            ToolsUsedId = 10
                        });
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.ToolUsed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("ToolsUsed");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "3Ds Max"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AutoCAD"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Revit"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Archicad"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lumion"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Photoshop"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Vray"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Corona"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Canon 6D"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sony Alpha 7Riii"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Nikon"
                        });
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.TopRatedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("TopRatedEntities");
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ce6f82b6-3d55-4bb3-8e94-d051a0b01a07",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a6d83be6-a45f-4861-bce9-cd7fe8d55455",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Yordan",
                            IsActive = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKcfuURWVb1SfAE+A3J7ufRDixRw0uGBGzrtI6ll8cbO1QUho+osXYJjeTdrnSQ2Sg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ca8023f-0abe-438e-8036-326e8238ab98",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "3c128b69-c44c-4c7d-9f7a-9921c86bbf29",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d4f9f832-23e3-4e52-9ad2-ca1a3e4bb1ef",
                            Email = "user@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Yordan",
                            IsActive = true,
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHNX/JM34zxWkbQiAVXJo9anMLsnPJa6TyGykK9hdamJHX/9vfkEccT6cp4aRfZv3w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47968690-6c08-4483-9f84-e278a8981fbb",
                            TwoFactorEnabled = false,
                            UserName = "user@gmail.com"
                        },
                        new
                        {
                            Id = "5faa7c98-430f-4036-928f-f5210e8fbeea",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ef554900-303f-4fa7-ae41-cd018022b31c",
                            Email = "moderator@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Yordan",
                            IsActive = true,
                            LastName = "Moderator",
                            LockoutEnabled = false,
                            NormalizedEmail = "MODERATOR@GMAIL.COM",
                            NormalizedUserName = "MODERATOR@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECwuxTGjoBWBJxGrIJ3qtM6dOLdYolFoCaWhPJL4GoSDRj06kYmp1nVio7pB2zVAhA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dec94dff-0d93-447f-9fe4-922cb758aa9f",
                            TwoFactorEnabled = false,
                            UserName = "moderator@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.ProjectEntity", b =>
                {
                    b.HasOne("DesignHelper.Infrastructure.Data.User", "AddToFavourites")
                        .WithMany()
                        .HasForeignKey("AddToFavouritesId");

                    b.HasOne("DesignHelper.Infrastructure.Data.AwardEntity", "Awards")
                        .WithMany("ProjectsWithAwards")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignHelper.Infrastructure.Data.Category", "Category")
                        .WithMany("Projects")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignHelper.Infrastructure.Data.TopRatedEntity", null)
                        .WithMany("Projects")
                        .HasForeignKey("TopRatedEntityId");

                    b.Navigation("AddToFavourites");

                    b.Navigation("Awards");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.ProjectToolsUsed", b =>
                {
                    b.HasOne("DesignHelper.Infrastructure.Data.ProjectEntity", "ProjectTools")
                        .WithMany("ProjectsToolsUsed")
                        .HasForeignKey("ProjectsEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignHelper.Infrastructure.Data.ToolUsed", "ToolsUsed")
                        .WithMany("ProjectsToolsUsed")
                        .HasForeignKey("ToolsUsedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectTools");

                    b.Navigation("ToolsUsed");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DesignHelper.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DesignHelper.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignHelper.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DesignHelper.Infrastructure.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.AwardEntity", b =>
                {
                    b.Navigation("ProjectsWithAwards");
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.Category", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.ProjectEntity", b =>
                {
                    b.Navigation("ProjectsToolsUsed");
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.ToolUsed", b =>
                {
                    b.Navigation("ProjectsToolsUsed");
                });

            modelBuilder.Entity("DesignHelper.Infrastructure.Data.TopRatedEntity", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
